
-- Seed categories
INSERT INTO public.categories (name, slug, description, image_url) VALUES
  ('Lehengas', 'lehengas', 'Mythology-inspired lehengas for the modern woman', null),
  ('Co-ord Sets', 'coord-sets', 'Matching sets that blend tradition with street style', null),
  ('Streetwear', 'streetwear', 'Heritage-infused everyday fashion', null);

-- Seed products
INSERT INTO public.products (name, slug, description, story, price, original_price, category_id, mythology_theme, sizes, colors, in_stock, is_featured, is_trending) VALUES
  ('Draupadi Lehenga', 'draupadi-lehenga', 'A stunning lehenga inspired by the strength and grace of Draupadi. Features intricate embroidery with modern silhouette.', 'Draupadi''s unshakeable spirit in the Mahabharata inspires this piece — a garment that refuses to unravel, much like the woman who wears it.', 12999.00, 15999.00, (SELECT id FROM categories WHERE slug='lehengas'), 'Mahabharata', '{XS,S,M,L,XL}', '{Royal Purple,Midnight Blue,Crimson Red}', true, true, true),
  ('Subhadra Silk Lehenga', 'subhadra-silk-lehenga', 'Flowing silk lehenga inspired by the elegance of Subhadra. Delicate gold thread detailing.', 'Subhadra — the bridge between warriors and wisdom. This piece flows like her quiet strength.', 14999.00, null, (SELECT id FROM categories WHERE slug='lehengas'), 'Mahabharata', '{S,M,L,XL}', '{Ivory Gold,Soft Rose}', true, true, false),
  ('Kunti Regal Lehenga', 'kunti-regal-lehenga', 'Regal lehenga paying homage to the wisdom and resilience of Kunti.', 'Kunti bore the weight of destiny with grace — this lehenga carries that same quiet power.', 16999.00, 19999.00, (SELECT id FROM categories WHERE slug='lehengas'), 'Mahabharata', '{XS,S,M,L}', '{Deep Emerald,Antique Gold}', true, false, true),
  ('Arjuna Co-ord Set', 'arjuna-coord-set', 'Sharp, focused co-ord set inspired by Arjuna''s precision. Modern cuts with mythological motifs.', 'Like Arjuna''s arrow, this set hits its mark — sharp lines, unwavering focus, effortless style.', 5999.00, 7999.00, (SELECT id FROM categories WHERE slug='coord-sets'), 'Mahabharata', '{XS,S,M,L,XL}', '{Charcoal,White,Navy}', true, true, true),
  ('Krishna Indigo Set', 'krishna-indigo-set', 'Playful yet powerful co-ord set in deep indigo tones inspired by Krishna''s divine energy.', 'Krishna''s flute played the music of the cosmos. This set plays with color and form in the same way.', 6499.00, null, (SELECT id FROM categories WHERE slug='coord-sets'), 'Mahabharata', '{S,M,L,XL}', '{Deep Indigo,Peacock Blue}', true, false, true),
  ('Gandhari Structured Set', 'gandhari-structured-set', 'Structured co-ord set reflecting Gandhari''s discipline and inner strength.', 'Gandhari chose darkness to share her husband''s world. This set is about choices made with fierce conviction.', 5499.00, 6999.00, (SELECT id FROM categories WHERE slug='coord-sets'), 'Mahabharata', '{XS,S,M,L}', '{Slate Grey,Muted Gold}', true, true, false),
  ('Karna Street Hoodie', 'karna-street-hoodie', 'Oversized hoodie with subtle Karna-inspired emblem. Comfort meets mythology.', 'Karna — the outsider who outshone them all. Wear your story on your sleeve, literally.', 2999.00, 3999.00, (SELECT id FROM categories WHERE slug='streetwear'), 'Mahabharata', '{S,M,L,XL,XXL}', '{Black,Olive,Burgundy}', true, true, true),
  ('Bheem Power Tee', 'bheem-power-tee', 'Bold graphic tee channeling Bheem''s raw power. Premium cotton with mythological art.', 'Bheem didn''t ask for permission — he simply was. This tee carries that same unapologetic energy.', 1999.00, null, (SELECT id FROM categories WHERE slug='streetwear'), 'Mahabharata', '{XS,S,M,L,XL,XXL}', '{White,Black,Forest Green}', true, false, true),
  ('Shakuntala Crop Top', 'shakuntala-crop-top', 'Delicate crop top with nature-inspired prints evoking Shakuntala''s forest origins.', 'Born of the forest, destined for the throne — Shakuntala''s duality lives in this piece.', 1799.00, 2499.00, (SELECT id FROM categories WHERE slug='streetwear'), 'Mahabharata', '{XS,S,M,L}', '{Sage Green,Cream,Terracotta}', true, true, false);
