// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmodzxbmhxprmkfdspzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptb2R6eGJtaHhwcm1rZmRzcHpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NDAzMDIsImV4cCI6MjA4NzQxNjMwMn0.TcrB_5QII1A4nEYnqkYXAotmMc7MD6LEIaMGo2Auc6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});